version: '{build}'

branches:
  only:
    - master

clone_folder: c:\projects\appveyor_test
image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013
configuration:
- RelWithDebInfo
platform:
- x64
- x86
environment:
  matrix:
  - arch: Win64
  - arch: Win32
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: false

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
build:
  project: c:\projects\appveyor_test\build\AppveyorTest.sln
  verbosity: minimal
  parallel: true
test_script:
  - c:\projects\appveyor_test\build\appveyor_test.exe
