version: '{build}'

branches:
  only:
    - master

clone_folder: c:\projects\appveyor_test
image:
- Visual Studio 2017
  #- Visual Studio 2015
  #- Visual Studio 2013
configuration:
- RelWithDebInfo

platform:
- Win32
- x64

environment:
  matrix:
  - arch: Win32
  - arch: Win64
  
matrix:
  exclude:
    - platform: x64
      arch: Win32
    - platform: Win32
      arch: Win64
  fast_finish: false

init:
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set vs=Visual Studio 15 2017)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set vs=Visual Studio 14 2015)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set vs=Visual Studio 12 2013)
- if "%arch%"=="Win64" ( set generator="%vs% Win64" )
- if "%arch%"=="Win32" ( set generator="%vs%" )
- echo %arch%
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
build:
  project: c:\projects\appveyor_test\build\AppveyorTest.sln
  verbosity: minimal
  parallel: true
test_script:
  - c:\projects\appveyor_test\build\RelWithDebInfo\appveyor_test.exe
